//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doulex.Pinyin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doulex.Pinyin.PinyinResource", typeof(PinyinResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // 本文件提供给汉字转拼音使用，不带声调
        ///// 如果要增加字或者词的时候，按照&quot;字词\t第一个字拼音|第二个字拼音|&quot;的格式
        ///// 字库中的多音字仅保留平凡使用的发音，词库枚举了多音字中其他发音组合的情况
        ///// 本字库从多个字词库整理而来
        ///// 如果文件中出现重复字词，而拼音不同，则取后者
        ///// 2008-07-10 Nepton 版本1.0
        ///吖	a|
        ///阿	a|
        ///啊	a|
        ///锕	a|
        ///錒	a|
        ///嗄	a|
        ///哎	ai|
        ///哀	ai|
        ///唉	ai|
        ///埃	ai|
        ///挨	ai|
        ///欸	ai|
        ///溾	ai|
        ///锿	ai|
        ///鎄	ai|
        ///啀	ai|
        ///捱	ai|
        ///皑	ai|
        ///凒	ai|
        ///嵦	ai|
        ///溰	ai|
        ///嘊	ai|
        ///敱	ai|
        ///敳	ai|
        ///皚	ai|
        ///癌	ai|
        ///毐	ai|
        ///昹	ai|
        ///娾	ai|
        ///嗳	ai|
        ///矮	ai|
        ///蔼	ai|
        ///躷	ai|
        ///噯	ai|
        ///濭	ai|
        ///﨟	ai|
        ///藹	ai|
        ///譪	ai|
        ///霭	ai|
        ///靄	ai|
        ///艾	ai|
        ///伌	ai|
        ///爱	ai|
        ///砹	ai|
        ///硋	ai|
        ///隘	ai|
        ///嗌	ai|
        ///塧	ai|
        ///嫒	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pinyin {
            get {
                return ResourceManager.GetString("Pinyin", resourceCulture);
            }
        }
    }
}
