version: '{build}'

environment:
  VERSION: 5.4.0
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022
platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|deploy|publish)/


before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\Doulex -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION% 

artifacts:
  - path: "src/**/*.nupkg"
    name: "NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
